# Generated by Django 2.0.1 on 2018-04-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180406_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretary',
            name='status',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
    ]
